service: creature

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  environment:
    APP_ID_LIST: 962124015,608659964,833967564,519581506,355832697

functions:
  check:
    handler: handler.check
    events:
      - schedule: rate(24 hours)
  # notify:
  #   handler: handler.notify
  #   events:
  #     - sns: new_releases

resources:
  Resources:
    releases_table:
      Type: AWS::DynamDB::Table
      Properties:
        TableName: creature_releases_table
        AttributeDefinitions:
          - AttributeName: app_id
            AttributeType: N
          - AttributeName: app_name
            AttributeType: S
          - AttributeName: version
            AttributeType: S
          - AttributeName: release_notes
            AttributeType: S
          - AttributeName: release_date
            AttributeType: S
          - AttributeName: raw_response
            AttributeType: S
        KeySchema:
          - AttributeName: app_id
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
    latest_releases:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: creature_latest_releases
        AttributeDefinitions:
          - AttributeName: app_id
            AttributeType: N
          - AttributeName: latest_version
            AttributeType: S
        KeySchema:
          - AttributeName: app_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 25
          WriteCapacityUnits: 25
